version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
      - pgadmin
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgresql-data:
  pgadmin-data: