version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: